//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopaDoMundo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CopaDoMundoEntities : DbContext
    {
        public CopaDoMundoEntities()
            : base("name=CopaDoMundoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alocacao> Alocacao { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Torcedor> Torcedor { get; set; }
        public virtual DbSet<AreaAlocacao> AreaAlocacao { get; set; }
        public virtual DbSet<TorcedorAlocado> TorcedorAlocado { get; set; }
    }
}
