//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copa_do_Mundo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alocacao
    {
        public int IDArea { get; set; }
        public int IDTor { get; set; }
        public Nullable<System.DateTime> DataAlocacao { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
