//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copa_do_Mundo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CopaDoMundoEntities : DbContext
    {
        public CopaDoMundoEntities()
            : base("name=CopaDoMundoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alocacao> Alocacao { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Torcedor> Torcedor { get; set; }
        public DbSet<AreaQtd> AreaQtd { get; set; }
    }
}
