//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copa_do_Mundo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torcedor
    {
        public int IDTor { get; set; }
        public string IDNome { get; set; }
        public string Idade { get; set; }
    }
}
